### ISSUE TITLE
Curve mode spreadsheet doesn't seem to match in-game progress

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/linearlevels#1]
Hi there! Firstly, thank you for making this mod!

I've been playing with this mod alongside [Deterministic XP bottles](https://modrinth.com/mod/deterministic-xp-bottles) and noticed that there's a discrepancy between experience needed to get to a certain level in-game and on the spreadsheet in the mod description.

The spreadsheet says 46 experience is required to reach level 4. To test this, I set the config in DXB to 50xp per bottle (which I've confirmed is working fine). Using a bottle at 0xp will get you to 3 levels and 14 points, suggesting it takes 36xp to reach level 3. The spreadsheet says it takes 32, so there's a difference of 4xp somewhere. I don't suppose you have an idea as to where this might come from?

**Comment by Partonetrain** [comment]
Good catch! With a cursory glance, it seems there's an off-by-one mistake in the spreadsheet's formulae. I will take a closer look and let you know.

**Comment by Partonetrain** [comment]
It's fixed, thank you for bringing this to my attention.
