### ISSUE TITLE
[Feature Request] Cap XP required for level up

### ISSUE THREAD

**Issue by lihaan** [Partonetrain/linearlevels#2]
Will be great if this mod can implement a simple cap on the XP required for a level up. This feature can be disabled by default, to prevent compatibility issues.

One great use case is setting the level up XP cap to 107, which is (via vanilla mechanics) the amount of XP required to get from lvl 29 to lvl 30. This will basically solve the whole issue of players being penalized for gaining more levels (just because they don't feel like enchanting at that point of time). This is also a much more seamless option, UX-wise, than having to use XP storage items from a different mod.

**Comment by Partonetrain** [comment]
This is a great idea, especially considering XP storage mods like Bottle Your Xp assume the vanilla conversions. I'll see if I can't implement this later this week.

**Comment by Partonetrain** [comment]
Uploading to CF/MR now.
