### ISSUE TITLE
Hard dependency on Mod Menu

### ISSUE THREAD

**Issue by anoomolu** [Partonetrain/linearlevels#5]
Hiya.

I was wondering if you'd be willing to drop the hard dependency on Mod Menu, given that the config is accessible from the config folder and [alternative](https://modrinth.com/mod/mod-settings) mod menus exist. No worries if not, in which case you may want to tag version 1.1.1 as requiring Mod Menu. Cheers ^^

**Comment by Partonetrain** [comment]
Ah, that explains the third issue. Yeah, I can take a look. I admit I forgot
about making ModMenu a requirement
